# Goal definition, in this case, a boolean
bool move
---
# Result definition, in this case, a boolean to indicate exit_status
bool exit_status
---
# Feedback definition, in this case, a progress percentage of how many markers have been travelle to
float32 percent_complete